name: odyssey-cli
services:
{{if .WithOdysseygo}}
  odysseygo:
    image: dionetech/odysseygo:{{ .OdysseygoVersion }}
{{if .E2E }}
    container_name: odysseygo{{.E2ESuffix}}
{{ else }}
    container_name: odysseygo
{{ end }}
    restart: unless-stopped
    user: "1000:1000"  # ubuntu user
    command: >
        ./odysseygo
        --config-file=/.odysseygo/configs/node.json
{{if .E2E }}
    volumes:
      - odysseygo_data_{{.E2ESuffix}}:/.odysseygo:rw
    ports:
      - "{{ .E2EIP }}:9650:9650"
      - "{{ .E2EIP }}:9651:9651"
    networks:
      - odysseygo_net_{{.E2ESuffix}}
{{ else }}
    volumes:
      - /home/ubuntu/.odysseygo:/.odysseygo:rw
    ports:
      - "9650:9650"
      - "9651:9651"
    network_mode: "host"
{{ end }}
{{ end }}

{{if .WithMonitoring}}
  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    restart: unless-stopped
    user: "1000:1000"  # ubuntu user
    command: -config.file=/etc/promtail/promtail.yml
{{if .E2E }}
    volumes:
      - odysseygo_logs_{{.E2ESuffix}}:/.odysseygo/logs:rw
      - /home/ubuntu/.odyssey-cli/services/promtail:/etc/promtail:ro
    networks:
      - odysseygo_net_{{.E2ESuffix}}
{{ else }}
    volumes:
      - /home/ubuntu/.odysseygo/logs:/logs:ro
      - /home/ubuntu/.odyssey-cli/services/promtail:/etc/promtail:ro
{{ end }}
  node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - "9100:9100"
{{if .WithOdysseygo}}
    links:
      - odysseygo
{{end}}
{{if .E2E }}
    networks:
      - odysseygo_net_{{.E2ESuffix}}
{{ end }}
{{end}}

{{if .E2E }}
volumes:
  odysseygo_data_{{.E2ESuffix}}:
  odysseygo_logs_{{.E2ESuffix}}:
networks:
  odysseygo_net_{{.E2ESuffix}}:
{{ end }}
    