name: odyssey-cli
services:
  awm-relayer:
    image: dionetech/awm-relayer
    container_name: awm-relayer
    restart: unless-stopped
    user: "1000:1000"  # ubuntu user
    network_mode: "host"
    volumes:
      - /home/ubuntu/.odyssey-cli/services/awm-relayer:/.awm-relayer:rw
    command: 'awm-relayer --config-file /.awm-relayer/awm-relayer-config.json'
