server:
  disable: true

positions:
  filename: /tmp/positions.yaml

clients:
- url: http://{{ .IP }}:{{ .Port}}/loki/api/v1/push


scrape_configs:
  - job_name: odysseygo
    pipeline_stages:
      - regex:
          expression: '\[(?P<timestamp>\d{2}-\d{2}\|\d{2}:\d{2}:\d{2}\.\d{3})\]'
      - timestamp:
          source: timestamp
          format: '03-20|01:34:31.515'
    static_configs:
    - targets:
        - localhost
      labels:
        job: d-chain
        host: {{ .Host }}
        nodeID: {{ .NodeID }}
        __path__: /logs/D.log
    - targets:
        - localhost
      labels:
        job: o-chain
        host: {{ .Host }}
        nodeID: {{ .NodeID }}
        __path__: /logs/O.log
    - targets:
        - localhost
      labels:
        job: a-chain
        host: {{ .Host }}
        nodeID: {{ .NodeID }}
        __path__: /logs/A.log
    - targets:
        - localhost
      labels:
        job: main
        host: {{ .Host }}
        nodeID: {{ .NodeID }}
        __path__: /logs/main.log
{{ if .ChainID }}
    - targets:
        - localhost
      labels:
        job: subnet
        host: {{ .Host }}
        nodeID: {{ .NodeID }}
        __path__: /logs/{{ .ChainID }}.log
{{ end }}
  - job_name: odysseygo-loadtest
    static_configs:
    - targets:
        - localhost
      labels:
        job: loadtest
        host: {{ .Host }}
        nodeID: {{ .NodeID }}
        __path__: /logs/loadtest_*.txt
